development:
  host: localhost
  database: barcamp_development

test:
  host: localhost
  database: barcamp_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>